on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
          who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       - name: Setup node
#         run: npm ci
#       - name: Hello world action step
#         id: hello
#         uses: ldhertert/node-action@v1.1
#         with:
#           who-to-greet: 'Mona the Octocat'
#       # Use the output from the `hello` step
#       - name: Get the output time
#         run: echo "The time was ${{ steps.hello.outputs.time }}"